#!/usr/bin/env python

BAUD_RATE = 9600
MOTOR_PORT = 'ttyACM0'
MAX_MOTOR_SPEED = 2047

WINCH_PORT = 'ttyUSB0'
WINCH_SPEED_FORW = 63
WINCH_SPEED_BACK = 127

ANCHOR_SPEED_FORW = 191
ANCHOR_SPEED_BACK = 255

GPS_PORT = '/dev/ttyACM0'
